"""Add relation from tags to modul.

Revision ID: 118823d0619
Revises: 443c2c3008dd
Create Date: 2014-03-24 15:18:20.701758

"""

# revision identifiers, used by Alembic.
revision = '118823d0619'
down_revision = '443c2c3008dd'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('mid', sa.Integer(), nullable=True))
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'mid')
    ### end Alembic commands ###
    iter_statements(DELETES)
