"""Removed comments module

Revision ID: 1aba8cde1f01
Revises: 4b9efcf216dc
Create Date: 2015-01-31 15:48:25.904895

"""

# revision identifiers, used by Alembic.
revision = '1aba8cde1f01'
down_revision = '4b9efcf216dc'

from alembic import op
import sqlalchemy as sa


UPGRADE = """
DELETE FROM "actions" WHERE mid = 11;
DELETE FROM "modules" WHERE id = 11;
"""
DOWNGRADE = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nm_form_comments')
    op.drop_table('comments')
    ### end Alembic commands ###
    iter_statements(UPGRADE)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    iter_statements(DOWNGRADE)
