"""Add gender field to profile.

Revision ID: 443c2c3008dd
Revises: 315908ef54fc
Create Date: 2014-03-18 16:31:37.221815

"""

# revision identifiers, used by Alembic.
revision = '443c2c3008dd'
down_revision = '315908ef54fc'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('gender', sa.Integer(), nullable=True))
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'gender')
    ### end Alembic commands ###
    iter_statements(DELETES)
