"""Add relation from blobform to modules

Revision ID: 4ee41432a71
Revises: 5a7b9035d52
Create Date: 2014-01-22 14:42:23.762718

"""

# revision identifiers, used by Alembic.
revision = '4ee41432a71'
down_revision = '5a7b9035d52'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('mid', sa.Integer(), nullable=True))
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'mid')
    ### end Alembic commands ###
    iter_statements(DELETES)
