"""Removed tags module

Revision ID: 52b4230d23fe
Revises: 1aba8cde1f01
Create Date: 2015-01-31 16:22:10.572782

"""

# revision identifiers, used by Alembic.
revision = '52b4230d23fe'
down_revision = '1aba8cde1f01'

from alembic import op
import sqlalchemy as sa


UPGRADE = """
DELETE FROM "actions" WHERE mid = 12;
DELETE FROM "modules" WHERE id = 12;
"""
DOWNGRADE = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nm_form_tags')
    op.drop_table('tags')
    ### end Alembic commands ###
    iter_statements(UPGRADE)


def downgrade():
    iter_statements(DOWNGRADE)
