"""0.9

Revision ID: 1b9688e1cc97
Revises: 1944ec2bb08
Create Date: 2013-12-05 14:51:39.548046

"""

# revision identifiers, used by Alembic.
revision = '1b9688e1cc97'
down_revision = '1944ec2bb08'

from alembic import op
import sqlalchemy as sa


INSERTS = """
INSERT INTO "modules" VALUES(11,'forms','ringo.model.form.Form','Form','Forms',NULL,NULL,'admin-menu');
INSERT INTO "actions" VALUES(48,11,'List','list','icon-list-alt',NULL);
INSERT INTO "actions" VALUES(49,11,'Create','create',' icon-plus',NULL);
INSERT INTO "actions" VALUES(50,11,'Read','read/{id}','icon-eye-open',NULL);
INSERT INTO "actions" VALUES(51,11,'Update','update/{id}','icon-edit',NULL);
INSERT INTO "actions" VALUES(52,11,'Delete','delete/{id}','icon-trash',NULL);
"""
DELETES = """
DELETE from modules where id = 11;
DELETE from actions where id = 48;
DELETE from actions where id = 49;
DELETE from actions where id = 50;
DELETE from actions where id = 51;
DELETE from actions where id = 52;
"""


def iter_statements(stmts):
    for st in stmts.split('\n'):
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gid', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gid'], ['usergroups.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forms')
    ### end Alembic commands ###
    iter_statements(DELETES)
