"""Added last_login column

Revision ID: 2e11045d6d2f
Revises: 23b6ea9b0966
Create Date: 2014-08-04 15:05:33.411053

"""

# revision identifiers, used by Alembic.
revision = '2e11045d6d2f'
down_revision = '23b6ea9b0966'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    ### end Alembic commands ###
    iter_statements(DELETES)
